### ISSUE TITLE
Dancer2::Core::Request doesn't verify whether it's actually behind a proxy if behind_proxy is set

### ISSUE THREAD

**Issue by wchristian** [PerlDancer/Dancer2#942]
When that variable is set in the config, Core::Request will try to use HTTP_X_FORWARDED_HOST, regardless of whether it is undefined or not. This causes warnings, and likely wrong behavior for dependents like uri_for.

**Comment by veryrusty** [comment]
Thanks for raising the issue @wchristian.

This was previously raised in #915, fixed by #930 and is awaiting the next release.

**Comment by wchristian** [comment]
In that case please reopen the fix issue, so users who actually DO search for things beforehand (like i did) can find them when they try to report them. Patched but unreleased should never be closed, since it's actually not fixed yet. (That's when you use labels instead.)

**Comment by xsawyerx** [comment]
@wchristian That's what *you* use labels for "instead". We use it to have details regarding what the issue is *about*, not whether it was fixed or not. We only have one label for the status of the ticket and that's whether it's obsolete or not.

We close tickets to know that we don't need to handle them anymore, because they were handled. We even explicitly have a label to mark that someone is working on them ("Claimed") so we know to look past it.

You can also search through closed tickets - something that is harder in RT but easier in Github Issues.

**Comment by wchristian** [comment]
> You can also search through closed tickets

That means people who report bugs for you need to actively remember to tick that box, and people who're doing it for the first time will likely not be aware of it, not do it and waste both their own and your time.

I guess i can understand that you don't care if the number of times that happens it's small enough, but from my point of view it's just a little impolite.

That said, feel free to ignore me, since i don't care to have an extended discussion on this if this is what your position is.

**Comment by xsawyerx** [comment]
"That means people who report bugs for you need to actively remember to tick that box, and people who're doing it for the first time will likely not be aware of it, not do it and waste both their own and your time."

Yes. That can happen. It happens once in a while. We explain it, it's understood, we're all happy and move on, and we try to get the next version released quicker.

"I guess i can understand that you don't care if the number of times that happens it's small enough, but from my point of view it's just a little impolite."

It does happen *very* rarely, so we're okay with it. I don't think it's impolite to optimize the bug list so we can actually fix bugs rather than make it optimized for a case that *rarely* happens. We go over the bug queue way more than often than someone opening a ticket for something that exists and we've yet to hear from a user who said "this is impolite!" - you are the first, and I honestly don't share your view.

"That said, feel free to ignore me, since i don't care to have an extended discussion on this if this is what your position is."

Opposite from ignoring you, I'm actually engaging with you. I'm explaining the reasoning behind the decision and how we see it. Describing it as "ignoring you" (if this is how you're describing it) is actually impolite.

I don't see room for an extended discussion, but one can always be attempted. We (the team - including myself) are always willing to reconsider our position.

**Comment by wchristian** [comment]
> Describing it as "ignoring you" (if this is how you're describing it) is actually impolite.

I was just trying to find a nicer way of saying this:

> I don't see room for an extended discussion

Sorry i didn't get it across clearly. :)

**Comment by xsawyerx** [comment]
I'll take that as me miscommunicating clearly. My apology. :)
